services:
  identman:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    image: identman
    environment:
      CONFIG: /opt/identman/config/config.yaml
      API_DECRYPT_PASSWORD: "Hallo"
      API_SALT: 2025
      API_CSRF_KEY: "TOP SECRET!!!"
    volumes:
      - ./config/:/opt/identman/config
      - ./identman:/opt/identman/identman
    ports:
      - "8000:8000"
    networks:
      - identnet

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        - VITE_API=http://127.0.0.1:8000
    image: identman-frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - identnet

networks:
  identnet:
    driver: bridge
